import { FoodItem } from '../types';

export const FOOD_DATABASE: FoodItem[] = [
  // Proteins & Meats
  {
    id: 'food_1',
    name: 'Grilled Chicken Breast',
    brand: 'Fresh Meat',
    calories: 165,
    proteinG: 31,
    carbsG: 0,
    fatG: 3.6,
    fiberG: 0,
    sugarG: 0,
    sodiumMg: 74,
    servingSize: 100,
    servingUnit: 'g',
    category: 'Proteins',
    icon: '🍗',
  },
  {
    id: 'food_2',
    name: 'Boiled Egg (Large)',
    brand: 'Farm Fresh',
    calories: 78,
    proteinG: 6.3,
    carbsG: 0.6,
    fatG: 5.3,
    fiberG: 0,
    sugarG: 0.6,
    sodiumMg: 62,
    servingSize: 1,
    servingUnit: 'large egg (50g)',
    category: 'Proteins',
    icon: '🥚',
  },
  {
    id: 'food_3',
    name: 'Egg Whites',
    brand: 'Pure',
    calories: 51,
    proteinG: 11,
    carbsG: 0.7,
    fatG: 0.2,
    fiberG: 0,
    sugarG: 0.7,
    sodiumMg: 166,
    servingSize: 100,
    servingUnit: 'g',
    category: 'Proteins',
    icon: '🍳',
  },
  {
    id: 'food_4',
    name: 'Atlantic Salmon (Pan-Seared)',
    brand: 'Seafood',
    calories: 206,
    proteinG: 22,
    carbsG: 0,
    fatG: 12.3,
    fiberG: 0,
    sugarG: 0,
    sodiumMg: 60,
    servingSize: 100,
    servingUnit: 'g',
    category: 'Proteins',
    icon: '🐟',
  },
  {
    id: 'food_5',
    name: 'Canned Tuna in Water',
    brand: 'Wild Caught',
    calories: 116,
    proteinG: 25.5,
    carbsG: 0,
    fatG: 0.8,
    fiberG: 0,
    sugarG: 0,
    sodiumMg: 247,
    servingSize: 100,
    servingUnit: 'g',
    category: 'Proteins',
    icon: '🥫',
  },
  {
    id: 'food_6',
    name: 'Lean Ground Beef (90/10)',
    brand: 'Butcher Shop',
    calories: 176,
    proteinG: 26,
    carbsG: 0,
    fatG: 7.7,
    fiberG: 0,
    sugarG: 0,
    sodiumMg: 66,
    servingSize: 100,
    servingUnit: 'g',
    category: 'Proteins',
    icon: '🥩',
  },
  {
    id: 'food_7',
    name: 'Greek Yogurt 0% Fat',
    brand: 'Chobani / Fage',
    calories: 100,
    proteinG: 18,
    carbsG: 6,
    fatG: 0,
    fiberG: 0,
    sugarG: 6,
    sodiumMg: 65,
    servingSize: 170,
    servingUnit: 'container (170g)',
    category: 'Dairy',
    icon: '🥛',
  },
  {
    id: 'food_8',
    name: 'Cottage Cheese (Low Fat)',
    brand: 'Good Culture',
    calories: 81,
    proteinG: 14,
    carbsG: 3.5,
    fatG: 1.2,
    fiberG: 0,
    sugarG: 3,
    sodiumMg: 364,
    servingSize: 100,
    servingUnit: 'g',
    category: 'Dairy',
    icon: '🧀',
  },
  {
    id: 'food_9',
    name: 'Firm Tofu',
    brand: 'Organic Soy',
    calories: 144,
    proteinG: 17.3,
    carbsG: 2.8,
    fatG: 8.7,
    fiberG: 2.3,
    sugarG: 0.5,
    sodiumMg: 14,
    servingSize: 100,
    servingUnit: 'g',
    category: 'Proteins',
    icon: '🧊',
  },
  {
    id: 'food_10',
    name: 'Whey Protein Powder',
    brand: 'Optimum Nutrition',
    calories: 120,
    proteinG: 24,
    carbsG: 3,
    fatG: 1.5,
    fiberG: 0,
    sugarG: 1,
    sodiumMg: 130,
    servingSize: 1,
    servingUnit: 'scoop (30g)',
    category: 'Supplements',
    icon: '🥤',
  },

  // Carbs & Grains
  {
    id: 'food_11',
    name: 'Brown Rice (Cooked)',
    brand: 'Whole Grain',
    calories: 216,
    proteinG: 5,
    carbsG: 45,
    fatG: 1.8,
    fiberG: 3.5,
    sugarG: 0.7,
    sodiumMg: 10,
    servingSize: 1,
    servingUnit: 'cup (195g)',
    category: 'Grains',
    icon: '🍚',
  },
  {
    id: 'food_12',
    name: 'White Jasmine Rice (Cooked)',
    brand: 'Grains',
    calories: 205,
    proteinG: 4.2,
    carbsG: 45,
    fatG: 0.4,
    fiberG: 0.6,
    sugarG: 0.1,
    sodiumMg: 0,
    servingSize: 1,
    servingUnit: 'cup (158g)',
    category: 'Grains',
    icon: '🍚',
  },
  {
    id: 'food_13',
    name: 'Rolled Oats (Raw)',
    brand: 'Quaker',
    calories: 150,
    proteinG: 5,
    carbsG: 27,
    fatG: 2.5,
    fiberG: 4,
    sugarG: 1,
    sodiumMg: 0,
    servingSize: 40,
    servingUnit: 'g (1/2 cup)',
    category: 'Grains',
    icon: '🥣',
  },
  {
    id: 'food_14',
    name: 'Sourdough Bread',
    brand: 'Artisan Bakery',
    calories: 120,
    proteinG: 4.5,
    carbsG: 24,
    fatG: 0.8,
    fiberG: 1.2,
    sugarG: 1,
    sodiumMg: 210,
    servingSize: 1,
    servingUnit: 'slice (50g)',
    category: 'Grains',
    icon: '🍞',
  },
  {
    id: 'food_15',
    name: 'Whole Wheat Bread',
    brand: 'Dave\'s Killer Bread',
    calories: 110,
    proteinG: 5,
    carbsG: 22,
    fatG: 1.5,
    fiberG: 3,
    sugarG: 2,
    sodiumMg: 170,
    servingSize: 1,
    servingUnit: 'slice (45g)',
    category: 'Grains',
    icon: '🍞',
  },
  {
    id: 'food_16',
    name: 'Sweet Potato (Baked)',
    brand: 'Fresh Produce',
    calories: 103,
    proteinG: 2.3,
    carbsG: 24,
    fatG: 0.2,
    fiberG: 3.8,
    sugarG: 7,
    sodiumMg: 41,
    servingSize: 1,
    servingUnit: 'medium (114g)',
    category: 'Vegetables',
    icon: '🍠',
  },
  {
    id: 'food_17',
    name: 'Quinoa (Cooked)',
    brand: 'Organic Grains',
    calories: 222,
    proteinG: 8.1,
    carbsG: 39.4,
    fatG: 3.6,
    fiberG: 5.2,
    sugarG: 1.6,
    sodiumMg: 13,
    servingSize: 1,
    servingUnit: 'cup (185g)',
    category: 'Grains',
    icon: '🌾',
  },
  {
    id: 'food_18',
    name: 'Whole Wheat Pasta (Cooked)',
    brand: 'Barilla',
    calories: 174,
    proteinG: 7.5,
    carbsG: 37,
    fatG: 0.8,
    fiberG: 6,
    sugarG: 1.5,
    sodiumMg: 4,
    servingSize: 1,
    servingUnit: 'cup (140g)',
    category: 'Grains',
    icon: '🍝',
  },

  // Healthy Fats & Nuts
  {
    id: 'food_19',
    name: 'Fresh Avocado',
    brand: 'Produce',
    calories: 160,
    proteinG: 2,
    carbsG: 8.5,
    fatG: 14.7,
    fiberG: 6.7,
    sugarG: 0.7,
    sodiumMg: 7,
    servingSize: 100,
    servingUnit: 'g (approx 1/2 avocado)',
    category: 'Fats',
    icon: '🥑',
  },
  {
    id: 'food_20',
    name: 'Peanut Butter (Natural)',
    brand: 'Smucker\'s',
    calories: 190,
    proteinG: 8,
    carbsG: 7,
    fatG: 16,
    fiberG: 2.5,
    sugarG: 2,
    sodiumMg: 5,
    servingSize: 2,
    servingUnit: 'tbsp (32g)',
    category: 'Fats',
    icon: '🥜',
  },
  {
    id: 'food_21',
    name: 'Almonds (Raw)',
    brand: 'Nuts',
    calories: 164,
    proteinG: 6,
    carbsG: 6.1,
    fatG: 14.2,
    fiberG: 3.5,
    sugarG: 1.2,
    sodiumMg: 1,
    servingSize: 28,
    servingUnit: 'g (about 23 almonds)',
    category: 'Fats',
    icon: '🌰',
  },
  {
    id: 'food_22',
    name: 'Extra Virgin Olive Oil',
    brand: 'Bertolli',
    calories: 119,
    proteinG: 0,
    carbsG: 0,
    fatG: 13.5,
    fiberG: 0,
    sugarG: 0,
    sodiumMg: 0,
    servingSize: 1,
    servingUnit: 'tbsp (14g)',
    category: 'Fats',
    icon: '🫒',
  },
  {
    id: 'food_23',
    name: 'Chia Seeds',
    brand: 'Superfood',
    calories: 138,
    proteinG: 4.7,
    carbsG: 12,
    fatG: 8.7,
    fiberG: 9.8,
    sugarG: 0,
    sodiumMg: 5,
    servingSize: 28,
    servingUnit: 'g (2 tbsp)',
    category: 'Fats',
    icon: '🌱',
  },

  // Fruits
  {
    id: 'food_24',
    name: 'Banana (Medium)',
    brand: 'Fresh Fruit',
    calories: 105,
    proteinG: 1.3,
    carbsG: 27,
    fatG: 0.3,
    fiberG: 3.1,
    sugarG: 14.4,
    sodiumMg: 1,
    servingSize: 1,
    servingUnit: 'medium (118g)',
    category: 'Fruits',
    icon: '🍌',
  },
  {
    id: 'food_25',
    name: 'Honeycrisp Apple',
    brand: 'Fresh Fruit',
    calories: 95,
    proteinG: 0.5,
    carbsG: 25,
    fatG: 0.3,
    fiberG: 4.4,
    sugarG: 19,
    sodiumMg: 2,
    servingSize: 1,
    servingUnit: 'medium (182g)',
    category: 'Fruits',
    icon: '🍎',
  },
  {
    id: 'food_26',
    name: 'Fresh Blueberries',
    brand: 'Berries',
    calories: 84,
    proteinG: 1.1,
    carbsG: 21,
    fatG: 0.5,
    fiberG: 3.6,
    sugarG: 15,
    sodiumMg: 1,
    servingSize: 1,
    servingUnit: 'cup (148g)',
    category: 'Fruits',
    icon: '🫐',
  },
  {
    id: 'food_27',
    name: 'Strawberries (Fresh)',
    brand: 'Berries',
    calories: 49,
    proteinG: 1,
    carbsG: 11.7,
    fatG: 0.5,
    fiberG: 3,
    sugarG: 7.4,
    sodiumMg: 1,
    servingSize: 1,
    servingUnit: 'cup sliced (166g)',
    category: 'Fruits',
    icon: '🍓',
  },
  {
    id: 'food_28',
    name: 'Orange (Navel)',
    brand: 'Citrus',
    calories: 69,
    proteinG: 1.3,
    carbsG: 17.6,
    fatG: 0.2,
    fiberG: 3.1,
    sugarG: 12,
    sodiumMg: 0,
    servingSize: 1,
    servingUnit: 'medium (140g)',
    category: 'Fruits',
    icon: '🍊',
  },

  // Vegetables
  {
    id: 'food_29',
    name: 'Steamed Broccoli',
    brand: 'Produce',
    calories: 55,
    proteinG: 3.7,
    carbsG: 11.2,
    fatG: 0.6,
    fiberG: 5.1,
    sugarG: 2.2,
    sodiumMg: 64,
    servingSize: 1,
    servingUnit: 'cup (156g)',
    category: 'Vegetables',
    icon: '🥦',
  },
  {
    id: 'food_30',
    name: 'Baby Spinach (Raw)',
    brand: 'Organic Greens',
    calories: 23,
    proteinG: 2.9,
    carbsG: 3.6,
    fatG: 0.4,
    fiberG: 2.2,
    sugarG: 0.4,
    sodiumMg: 79,
    servingSize: 100,
    servingUnit: 'g (about 3 cups)',
    category: 'Vegetables',
    icon: '🥬',
  },

  // Popular Meals & Fast Fitness Dishes
  {
    id: 'food_31',
    name: 'Chipotle Chicken Burrito Bowl',
    brand: 'Chipotle',
    calories: 680,
    proteinG: 48,
    carbsG: 64,
    fatG: 24,
    fiberG: 14,
    sugarG: 4,
    sodiumMg: 1420,
    servingSize: 1,
    servingUnit: 'bowl (450g)',
    category: 'Meals',
    icon: '🌯',
  },
  {
    id: 'food_32',
    name: 'Avocado Toast with 2 Poached Eggs',
    brand: 'Brunch',
    calories: 420,
    proteinG: 18,
    carbsG: 32,
    fatG: 26,
    fiberG: 8,
    sugarG: 3,
    sodiumMg: 450,
    servingSize: 1,
    servingUnit: 'plate',
    category: 'Meals',
    icon: '🥑',
  },
  {
    id: 'food_33',
    name: 'Salmon Poke Bowl with Sushi Rice',
    brand: 'Poke Bar',
    calories: 580,
    proteinG: 34,
    carbsG: 68,
    fatG: 18,
    fiberG: 6,
    sugarG: 8,
    sodiumMg: 890,
    servingSize: 1,
    servingUnit: 'bowl (420g)',
    category: 'Meals',
    icon: '🥗',
  },
  {
    id: 'food_34',
    name: 'Protein Oatmeal with Berries & PB',
    brand: 'Fit Breakfast',
    calories: 395,
    proteinG: 28,
    carbsG: 46,
    fatG: 11,
    fiberG: 8,
    sugarG: 9,
    sodiumMg: 160,
    servingSize: 1,
    servingUnit: 'bowl',
    category: 'Meals',
    icon: '🥣',
  },
  {
    id: 'food_35',
    name: 'Margherita Pizza Slice',
    brand: 'Italian',
    calories: 270,
    proteinG: 12,
    carbsG: 32,
    fatG: 10,
    fiberG: 2,
    sugarG: 3,
    sodiumMg: 560,
    servingSize: 1,
    servingUnit: 'slice (107g)',
    category: 'Meals',
    icon: '🍕',
  },
  {
    id: 'food_36',
    name: 'American Cheeseburger',
    brand: 'Diner',
    calories: 535,
    proteinG: 30,
    carbsG: 40,
    fatG: 28,
    fiberG: 2,
    sugarG: 7,
    sodiumMg: 980,
    servingSize: 1,
    servingUnit: 'burger (220g)',
    category: 'Meals',
    icon: '🍔',
  },
  {
    id: 'food_37',
    name: 'Chicken Caesar Salad',
    brand: 'Fresh Kitchen',
    calories: 380,
    proteinG: 32,
    carbsG: 12,
    fatG: 22,
    fiberG: 4,
    sugarG: 3,
    sodiumMg: 780,
    servingSize: 1,
    servingUnit: 'large bowl (350g)',
    category: 'Meals',
    icon: '🥗',
  },
  {
    id: 'food_38',
    name: 'Iced Oat Latte (Unsweetened)',
    brand: 'Cafe',
    calories: 120,
    proteinG: 3,
    carbsG: 16,
    fatG: 5,
    fiberG: 2,
    sugarG: 7,
    sodiumMg: 100,
    servingSize: 1,
    servingUnit: 'grande (16 fl oz)',
    category: 'Beverages',
    icon: '☕',
  },
  {
    id: 'food_39',
    name: 'Dark Chocolate 85%',
    brand: 'Lindt',
    calories: 170,
    proteinG: 3,
    carbsG: 12,
    fatG: 14,
    fiberG: 4,
    sugarG: 4,
    sodiumMg: 10,
    servingSize: 30,
    servingUnit: 'g (3 squares)',
    category: 'Snacks',
    icon: '🍫',
  },
  {
    id: 'food_40',
    name: 'Hummus & Pita Chips',
    brand: 'Sabra & Stacy\'s',
    calories: 220,
    proteinG: 6,
    carbsG: 26,
    fatG: 10,
    fiberG: 3,
    sugarG: 1,
    sodiumMg: 340,
    servingSize: 1,
    servingUnit: 'snack pack (60g)',
    category: 'Snacks',
    icon: '🥙',
  },
  {
    id: 'food_41',
    name: 'Chicken Biryani',
    brand: 'Home Style',
    calories: 490,
    proteinG: 26,
    carbsG: 62,
    fatG: 15,
    fiberG: 3,
    sugarG: 2,
    sodiumMg: 820,
    servingSize: 1,
    servingUnit: 'plate (350g)',
    category: 'Meals',
    icon: '🍛',
  },
  {
    id: 'food_42',
    name: 'Paneer Butter Masala with 1 Naan',
    brand: 'Indian Cuisine',
    calories: 620,
    proteinG: 22,
    carbsG: 58,
    fatG: 34,
    fiberG: 5,
    sugarG: 6,
    sodiumMg: 940,
    servingSize: 1,
    servingUnit: 'serving',
    category: 'Meals',
    icon: '🥘',
  },
  {
    id: 'food_43',
    name: 'Sushi Roll (California Roll 8 pcs)',
    brand: 'Japanese',
    calories: 330,
    proteinG: 9,
    carbsG: 42,
    fatG: 12,
    fiberG: 4,
    sugarG: 6,
    sodiumMg: 680,
    servingSize: 8,
    servingUnit: 'pieces',
    category: 'Meals',
    icon: '🍱',
  },
  {
    id: 'food_44',
    name: 'Protein Bar (Chocolate Peanut Butter)',
    brand: 'Barebells / Quest',
    calories: 200,
    proteinG: 20,
    carbsG: 17,
    fatG: 8,
    fiberG: 10,
    sugarG: 1.5,
    sodiumMg: 190,
    servingSize: 1,
    servingUnit: 'bar (55g)',
    category: 'Snacks',
    icon: '🍫',
  },
];

export const FOOD_CATEGORIES = [
  'All',
  'Proteins',
  'Grains',
  'Fruits',
  'Vegetables',
  'Dairy',
  'Fats',
  'Meals',
  'Snacks',
  'Beverages',
  'Supplements',
];

export const PRESET_MEAL_IMAGES = [
  {
    title: 'Grilled Salmon with Quinoa & Asparagus',
    description: 'Fresh grilled salmon filet, cooked fluffy quinoa, roasted tender green asparagus',
    category: 'dinner' as const,
    calories: 520,
    proteinG: 38,
    carbsG: 36,
    fatG: 22,
    image: 'https://images.unsplash.com/photo-1467003909585-2f8a72700288?auto=format&fit=crop&w=600&q=80',
  },
  {
    title: 'Avocado Toast with Poached Eggs & Microgreens',
    description: 'Crispy sourdough toast, smashed ripe avocado, two poached eggs with chili flakes',
    category: 'breakfast' as const,
    calories: 430,
    proteinG: 19,
    carbsG: 32,
    fatG: 26,
    image: 'https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format&fit=crop&w=600&q=80',
  },
  {
    title: 'Chicken Protein Power Bowl with Black Beans',
    description: 'Charred seasoned chicken breast, brown rice, black beans, corn salsa, avocado slices',
    category: 'lunch' as const,
    calories: 640,
    proteinG: 46,
    carbsG: 68,
    fatG: 20,
    image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=600&q=80',
  },
  {
    title: 'Acai Berry Smoothie Bowl with Granola & Chia',
    description: 'Thick organic acai blend topped with sliced bananas, blueberries, organic honey, chia seeds',
    category: 'breakfast' as const,
    calories: 360,
    proteinG: 8,
    carbsG: 64,
    fatG: 9,
    image: 'https://images.unsplash.com/photo-1590301157890-4810ed352733?auto=format&fit=crop&w=600&q=80',
  },
  {
    title: 'Japanese Ahi Tuna Poke Bowl',
    description: 'Fresh diced ahi tuna, edamame, cucumber, pickled ginger, seaweed salad, sushi rice',
    category: 'lunch' as const,
    calories: 550,
    proteinG: 36,
    carbsG: 62,
    fatG: 16,
    image: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=600&q=80',
  },
];
